### ISSUE TITLE
Warn on mismatched versions

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1678]
Issues can arise when clients and workers don't agree on versions of libraries like cloudpickle .  This is a common user issue.

We often recommend calling `client.get_versions(check=True)` which errs in a very informative way when versions do not match.  We have talked about running this automatically on startup but have avoided it so far.

Perhaps we should run this, but just warn instead of err.  I propose the following:

1.  Support warning rather than erring in get_versions with `get_versions(check='warn')`.  Valid arguments to this would be `'warn', 'err', 'error', and True` the last three of which would all alias to the same behavior.
2.  Call get_versions in `client._start`
3.  Remove this functionality when automatically starting clients, such as in `worker.py::get_client()` or `Future.__setstate__`

**Comment by jcrist** [comment]
+1. We've also struggled with this, frequently errors are due to mismatched environments.

> Support warning rather than erring in get_versions with get_versions(check='warn'). Valid arguments to this would be 'warn', 'err', 'error', and True the last three of which would all alias to the same behavior.

I'd tweak this slightly to be `get_versions(check=False)` (current default remains the same), and remove the `'err'` alias which I think is more confusing than just `'error'` and `'warn'` (on first glance I wondered what the difference was).

**Comment by mrocklin** [comment]
The suggestions look good to me

**Comment by andybrnr** [comment]
+1. I've just begun exploring using on demand k8s clusters with a DASK deployment to accelerate large computations for our DS group. When working through these nice tutorials ([here](https://ramhiser.com/post/2018-05-20-setting-up-a-kubernetes-cluster-on-aws-in-5-minutes/) and [here](https://ramhiser.com/post/2018-05-28-adding-dask-and-jupyter-to-kubernetes-cluster/)), I ended up with a version mismatch when using [the minimal example config.yaml from the DASK docs](http://dask.pydata.org/en/latest/setup/kubernetes-helm.html?highlight=configure%20yaml). Mismatch was on the client side, which I think perhaps flowed through from adding matplotlib on the container with the jupyter server and not on the workers. Is there a best practice approach to assure versions stay matched, or am I missing something?

**Comment by mrocklin** [comment]
Currently no best practices exist.  Something like an automatic check on starting a client is the most advanced proposal we've seen so far.  Do you have any other suggestions?

**Comment by andybrnr** [comment]
Still enough of a n00b with both DASK and containerized networking/cluster management that I don't think I'm qualified to have suggestions :) As I mess around with this more, I'll do my best to try and come up with coherent thoughts.

**Comment by mrocklin** [comment]
The world is new to these problems :)  Your thoughts would be welcome at
any point, coherent or otherwise.

**Comment by andybrnr** [comment]
I'm probably going to rapidly reveal my ignorance here - feel free to redirect me to a different support channel as appropriate. So I've spun up a cluster per the linked tutorial, deployed DASK via helm, and then tried to upgrade the cluster with the config.yaml linked above from the docs, only modified such that matplotlib was included on the workers as well, just in case the version mismatch observed between the client and workers/scheduler was rooted in some dependency issue there. After the upgrade command is issued, I've waited a while, and helm status gives me the following: 

```
andrewberner$ helm status braided-clam
LAST DEPLOYED: Mon Jul 30 15:25:34 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME                         TYPE          CLUSTER-IP      EXTERNAL-IP       PORT(S)                      AGE
braided-clam-dask-jupyter    LoadBalancer  100.67.255.104  a2a3387379441...  80:30874/TCP                 1h
braided-clam-dask-scheduler  LoadBalancer  100.69.46.120   a2a4240a39441...  8786:31053/TCP,80:32076/TCP  1h

==> v1beta2/Deployment
NAME                         DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
braided-clam-dask-jupyter    1        1        1           1          1h
braided-clam-dask-scheduler  1        1        1           1          1h
braided-clam-dask-worker     6        8        3           5          1h

==> v1/Pod(related)
NAME                                          READY  STATUS   RESTARTS  AGE
braided-clam-dask-jupyter-8456d8656f-pm456    1/1    Running  0         25m
braided-clam-dask-scheduler-766cd69984-dzd7c  1/1    Running  0         1h
braided-clam-dask-worker-6dd6dd8974-6w4hw     1/1    Running  0         1h
braided-clam-dask-worker-6dd6dd8974-9mf87     1/1    Running  0         25m
braided-clam-dask-worker-6dd6dd8974-fxzh2     1/1    Running  0         1h
braided-clam-dask-worker-6dd6dd8974-jp64x     1/1    Running  0         25m
braided-clam-dask-worker-6dd6dd8974-s8pm8     1/1    Running  0         1h
braided-clam-dask-worker-767789f5f9-689w7     0/1    Pending  0         25m
braided-clam-dask-worker-767789f5f9-dc7mx     0/1    Pending  0         25m
braided-clam-dask-worker-767789f5f9-gxfp2     0/1    Pending  0         25m

==> v1/ConfigMap
NAME                              DATA  AGE
braided-clam-dask-jupyter-config  1     1h


NOTES:
Thank you for installing DASK, released at name: braided-clam.

To learn more about the release, try:

  $ helm status braided-clam  # information about running pods and this message
  $ helm get braided-clam     # get full Kubernetes specification

This release includes a Dask scheduler, 6 Dask workers, and 1 Jupyter servers.  

The Jupyter notebook server and Dask scheduler expose external services to
which you can connect to manage notebooks, or connect directly to the Dask
cluster.   You can get these addresses by running the following:

  export DASK_SCHEDULER=$(kubectl get svc --namespace default braided-clam-dask-scheduler -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  export DASK_SCHEDULER_UI_IP=$(kubectl get svc --namespace default braided-clam-dask-scheduler -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  export JUPYTER_NOTEBOOK_IP=$(kubectl get svc --namespace default braided-clam-dask-jupyter -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  echo http://$JUPYTER_NOTEBOOK_IP:80 -- Jupyter notebook
  echo http://$DASK_SCHEDULER_UI_IP:80  -- Dask dashboard
  echo http://$DASK_SCHEDULER:8786    -- Dask Client connection

  NOTE: The default password to login to the notebook server is `dask`.

  NOTE: It may take a few minutes for the LoadBalancer IP to be available, until that the commands below will not work.  
  You can watch the status by running 'kubectl get svc --namespace default -w braided-clam-dask-jupyter'
```

First observation - the cluster config doesn't seem to reach the desired state, as the upgrade command generates three new worker pods that are permanently pending. Not sure whether that relates to not having enough resources on my underlying physical cluster of one m3.medium master and two t2.medium nodes?

Second observation - I dumped the full k8s target spec helm has generated via helm get <cluster-name>. I end up with the following:

```
andrewberner$ helm get braided-clam
REVISION: 2
RELEASED: Mon Jul 30 15:25:34 2018
CHART: dask-1.0.4
USER-SUPPLIED VALUES:
jupyter:
  enabled: true
  env:
  - name: EXTRA_CONDA_PACKAGES
    value: numba xarray matplotlib -c conda-forge
  - name: EXTRA_PIP_PACKAGES
    value: s3fs gcsfs dask-ml --upgrade
worker:
  env:
  - name: EXTRA_CONDA_PACKAGES
    value: numba xarray matplotlib -c conda-forge
  - name: EXTRA_PIP_PACKAGES
    value: s3fs gcsfs dask-ml --upgrade
  replicas: 6
  resources:
    limits:
      cpu: 2
      memory: 7.5G
    requests:
      cpu: 2
      memory: 7.5G

COMPUTED VALUES:
jupyter:
  enabled: true
  env:
  - name: EXTRA_CONDA_PACKAGES
    value: numba xarray matplotlib -c conda-forge
  - name: EXTRA_PIP_PACKAGES
    value: s3fs gcsfs dask-ml --upgrade
  image:
    pullPolicy: IfNotPresent
    repository: daskdev/dask-notebook
    tag: 0.17.4
  name: jupyter
  password: sha1:aae8550c0a44:9507d45e087d5ee481a5ce9f4f16f37a0867318c
  replicas: 1
  resources: {}
  servicePort: 80
  serviceType: LoadBalancer
scheduler:
  image:
    pullPolicy: IfNotPresent
    repository: daskdev/dask
    tag: 0.17.4
  name: scheduler
  replicas: 1
  resources: {}
  servicePort: 8786
  serviceType: LoadBalancer
webUI:
  name: webui
  servicePort: 80
worker:
  aptPackages: ""
  default_resources:
    cpu: 1
    memory: 4GiB
  env:
  - name: EXTRA_CONDA_PACKAGES
    value: numba xarray matplotlib -c conda-forge
  - name: EXTRA_PIP_PACKAGES
    value: s3fs gcsfs dask-ml --upgrade
  image:
    pullPolicy: IfNotPresent
    repository: daskdev/dask
    tag: 0.17.4
  name: worker
  replicas: 6
  resources:
    limits:
      cpu: 2
      memory: 7.5G
    requests:
      cpu: 2
      memory: 7.5G

HOOKS:
MANIFEST:

---
# Source: dask/templates/dask-jupyter-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: braided-clam-dask-jupyter-config
  labels:
    app: dask
    heritage: "Tiller"
    release: "braided-clam"
    chart: dask-1.0.4
    component: jupyter
data:
  jupyter_notebook_config.py: |
    c = get_config()
    c.NotebookApp.password = 'sha1:aae8550c0a44:9507d45e087d5ee481a5ce9f4f16f37a0867318c'
---
# Source: dask/templates/dask-jupyter-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: braided-clam-dask-jupyter
  labels:
    app: dask
    heritage: "Tiller"
    release: "braided-clam"
    chart: dask-1.0.4
    component: jupyter
spec:
  ports:
    - port: 80
      targetPort: 8888
  selector:
    app: dask
    release: "braided-clam"
    component: jupyter
  type: LoadBalancer
---
# Source: dask/templates/dask-scheduler-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: braided-clam-dask-scheduler
  labels:
    app: dask
    heritage: "Tiller"
    release: "braided-clam"
    chart: dask-1.0.4
    component: scheduler
spec:
  ports:
    - name: braided-clam-dask-scheduler
      port: 8786
      targetPort: 8786
    - name: braided-clam-dask-webui
      port: 80
      targetPort: 8787
  selector:
    app: dask
    release: "braided-clam"
    component: scheduler
  type: LoadBalancer
---
# Source: dask/templates/dask-jupyter-deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: braided-clam-dask-jupyter
  labels:
    app: dask
    heritage: "Tiller"
    release: "braided-clam"
    chart: dask-1.0.4
    component: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask
      release: "braided-clam"
      component: jupyter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dask
        release: "braided-clam"
        component: jupyter
    spec:
      containers:
        - name: braided-clam-dask-jupyter
          image: "daskdev/dask-notebook:0.17.4"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          resources:
            {}
            
          volumeMounts:
            - name: config-volume
              mountPath: /home/jovyan/.jupyter
          env:
            - name: DASK_SCHEDULER_ADDRESS
              value: braided-clam-dask-scheduler:8786
            - name: EXTRA_CONDA_PACKAGES
              value: numba xarray matplotlib -c conda-forge
            - name: EXTRA_PIP_PACKAGES
              value: s3fs gcsfs dask-ml --upgrade
            
      volumes:
        - name: config-volume
          configMap:
            name: braided-clam-dask-jupyter-config
---
# Source: dask/templates/dask-scheduler-deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: braided-clam-dask-scheduler
  labels:
    app: dask
    heritage: "Tiller"
    release: "braided-clam"
    chart: dask-1.0.4
    component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask
      release: "braided-clam"
      component: scheduler
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dask
        release: "braided-clam"
        component: scheduler
    spec:
      containers:
        - name: braided-clam-dask-scheduler
          image: "daskdev/dask:0.17.4"
          imagePullPolicy: IfNotPresent
          args:
            - dask-scheduler
            - --port
            - "8786"
            - --bokeh-port
            - "8787"
          ports:
            - containerPort: 8786
            - containerPort: 8787
          resources:
            {}
            
          env:
            null
---
# Source: dask/templates/dask-worker-deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: braided-clam-dask-worker
  labels:
    app: dask
    heritage: "Tiller"
    release: "braided-clam"
    chart: dask-1.0.4
    component: worker
spec:
  replicas: 6
  selector:
    matchLabels:
      app: dask
      release: "braided-clam"
      component: worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dask
        release: "braided-clam"
        component: worker
    spec:
      containers:
        - name: braided-clam-dask-worker
          image: "daskdev/dask:0.17.4"
          imagePullPolicy: IfNotPresent
          args:
            - dask-worker
            - braided-clam-dask-scheduler:8786
            - --nthreads
            - "2"
            - --memory-limit
            - "7.5G"
            - --no-bokeh
          ports:
            - containerPort: 8789
          resources:
            limits:
              cpu: 2
              memory: 7.5G
            requests:
              cpu: 2
              memory: 7.5G
            
          env:
            - name: EXTRA_CONDA_PACKAGES
              value: numba xarray matplotlib -c conda-forge
            - name: EXTRA_PIP_PACKAGES
              value: s3fs gcsfs dask-ml --upgrade
```

All well and good, desired packages/versions look consistent across the scheduler, workers, and jupyter pods. But when I go into the jupyter interface and run client.get_versions(check=True), I now get this:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-48bbb7b1dc08> in <module>()
----> 1 c.get_versions(check=True)

/opt/conda/lib/python3.6/site-packages/distributed/client.py in get_versions(self, check)
   3034                 raise ValueError("Mismatched versions found\n"
   3035                                  "\n"
-> 3036                                  "%s" % ('\n\n'.join(errs)))
   3037 
   3038         return result

ValueError: Mismatched versions found

blosc
+------------------------+---------+
|                        | version |
+------------------------+---------+
| client                 | 1.4.4   |
| scheduler              | 1.5.1   |
| tcp://100.96.1.5:36964 | 1.5.1   |
| tcp://100.96.1.6:38415 | 1.5.1   |
| tcp://100.96.2.6:44389 | 1.5.1   |
| tcp://100.96.2.7:39214 | 1.5.1   |
| tcp://100.96.2.8:40317 | 1.5.1   |
+------------------------+---------+

cloudpickle
+------------------------+---------+
|                        | version |
+------------------------+---------+
| client                 | 0.5.3   |
| scheduler              | 0.5.2   |
| tcp://100.96.1.5:36964 | 0.5.2   |
| tcp://100.96.1.6:38415 | 0.5.2   |
| tcp://100.96.2.6:44389 | 0.5.2   |
| tcp://100.96.2.7:39214 | 0.5.2   |
| tcp://100.96.2.8:40317 | 0.5.2   |
+------------------------+---------+

dask
+------------------------+---------+
|                        | version |
+------------------------+---------+
| client                 | 0.18.2  |
| scheduler              | 0.17.4  |
| tcp://100.96.1.5:36964 | 0.17.4  |
| tcp://100.96.1.6:38415 | 0.17.4  |
| tcp://100.96.2.6:44389 | 0.17.4  |
| tcp://100.96.2.7:39214 | 0.17.4  |
| tcp://100.96.2.8:40317 | 0.17.4  |
+------------------------+---------+

numpy
+------------------------+---------+
|                        | version |
+------------------------+---------+
| client                 | 1.15.0  |
| scheduler              | 1.14.2  |
| tcp://100.96.1.5:36964 | 1.14.2  |
| tcp://100.96.1.6:38415 | 1.14.2  |
| tcp://100.96.2.6:44389 | 1.14.2  |
| tcp://100.96.2.7:39214 | 1.14.2  |
| tcp://100.96.2.8:40317 | 1.14.2  |
+------------------------+---------+

pandas
+------------------------+---------+
|                        | version |
+------------------------+---------+
| client                 | 0.23.3  |
| scheduler              | 0.22.0  |
| tcp://100.96.1.5:36964 | 0.22.0  |
| tcp://100.96.1.6:38415 | 0.22.0  |
| tcp://100.96.2.6:44389 | 0.22.0  |
| tcp://100.96.2.7:39214 | 0.22.0  |
| tcp://100.96.2.8:40317 | 0.22.0  |
+------------------------+---------+

tornado
+------------------------+---------+
|                        | version |
+------------------------+---------+
| client                 | 4.5.2   |
| scheduler              | 5.0.2   |
| tcp://100.96.1.5:36964 | 5.0.2   |
| tcp://100.96.1.6:38415 | 5.0.2   |
| tcp://100.96.2.6:44389 | 5.0.2   |
| tcp://100.96.2.7:39214 | 5.0.2   |
| tcp://100.96.2.8:40317 | 5.0.2   |
+------------------------+---------+
```

So the running jupyter pod configuration doesn't match what's in the helm spec. Any thoughts?
