### ISSUE TITLE
TLS configuration for dask scheduler via CLI options is broken

### ISSUE THREAD

**Issue by Corni** [dask/distributed#1696]
Hi,

when configuring TLS for distributed schedulers via the command line, the CLI options are ignored, but setting a DASK_CONFIG works.

```
vagrant@base-jessie /vagrant % dask-scheduler --tls-ca-file /vagrant/ca-cert.crt --tls-cert /vagrant/server2.crt --tls-key /vagrant/server2.key
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:      tcp://10.0.2.15:8786
distributed.scheduler - INFO - Local Directory:      /tmp/scheduler-SRqPuw
distributed.scheduler - INFO - -----------------------------------------------
^Cdistributed.scheduler - INFO - End scheduler at 'tcp://:8786'
vagrant@base-jessie /vagrant % DASK_CONFIG=config-scheduler.yaml dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:      tls://10.0.2.15:8786
distributed.scheduler - INFO - Local Directory:      /tmp/scheduler-eZbsAo
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Register tls://10.0.2.15:51975
distributed.scheduler - INFO - Starting worker compute stream, tls://10.0.2.15:51975
^Cdistributed.scheduler - INFO - End scheduler at 'tls://:8786'
vagrant@base-jessie /vagrant %
```

and config-scheduler.yaml contains
```
logging:
    distributed: info
    distributed.client: warning
    bokeh: critical

default-scheme: tls
tls:
    ca-file: /vagrant/ca-cert.crt
    scheduler:
        cert: /vagrant/server2.crt
        key: /vagrant/server2.key

```

As can be seen, the first server starts in tcp mode, while the second starts in tls mode, with the options being essentially the same.
If needed, I can provide the certificates and keys, as this is a test installation anyways.
