### ISSUE TITLE
Significant CPU usage when cluster is idle on large machine

### ISSUE THREAD

**Issue by emaror** [dask/distributed#2079]
I think it is identical to #1313, but that one was closed.
I am spinning up a cluster from withing a Jupyter notebook, on a 24 core machine (rhel 6). Python version 2.7.6, dask.distributed version 1.22.0

After running 

```
import dask.distributed
cluster = dask.dstributed.LocalCluster(local_dir='/path/to/a/local/disk/')
```
in the notebook, there are 24 dask workers taking ~9% CPU *each*, the kernel itself is taking ~15%.

Doing an strace on the workers shows that they are doing:

```
epoll_wait(185, {}, 1023, 0)            = 0
```

my ~/.dask/config is:

```
logging: 
  distributed: info 
  distributed.client: info
  bokeh: info

compression: auto

# Scheduler options
bandwidth: 100000000    # 100 MB/s estimated worker-worker bandwidth
allowed-failures: 3     # number of retries before a task is considered bad
pdb-on-err: False       # enter debug mode on scheduling error
transition-log-length: 100000 
use-file-locking: False
#multiprocessing-method: forkserver
````
