### ISSUE TITLE
Alternate themes for the dashboard

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#2305]
People may prefer different themes for the dashboard.  This both allows individual style to come out, and also exposes a nice laboritory for others to explore and create better visual style than we can.  (which we can then steal as defaults).

There are a few places where we currently specify colors and styling:

1.  In the bokeh [theme.yaml](https://github.com/dask/distributed/blob/master/distributed/bokeh/theme.yaml) .  This determines the style of the bokeh figures, except what we specify in code
2.  In the code, where we specify colors explicitly (for example we currently have hard-coded values for "blue", "red" and "Viridis11" within our codecase.  See https://github.com/dask/distributed/blob/a78109e3605756562dc7caed4608db5e99b8dbd0/distributed/bokeh/scheduler.py#L441-L444
3.  In [static/css/base.css](https://github.com/dask/distributed/blob/master/distributed/bokeh/static/css/base.css) where we specify background color, and color for the navbar

Currently if you want to build a new theme you'll need to touch all of these.  Once you've built that theme it's not easy to switch back and forth.  

What is the right way to represent styling so that people can easily experiment with it and switch back and forth without having to repackage things?

cc @canavandl

**Comment by mrocklin** [comment]
Here is a proposal

We can put Bokeh's theme.yaml and a few other elements into a [Dask config file](http://docs.dask.org/en/latest/configuration.html) (just yaml files that we store in `~/.config/dask/`).  This file might be organized as follows:

```yaml
dashboard:
  theme: name-of-theme

  name-of-theme: 
    css: path/to/my.css
    colors:
      task-stream-palette: Viridis11
      good: blue
      stressed: red
      critical: black

    bokeh-theme:
      ...  # normal bokeh theme.yaml follows

  name-of-second-theme:
    ...

  name-of-third-theme:
    ..
```

We'll then have to access these elements through `dask.config.get('dashboard')`, pick out the right sub-yaml block to read, and then refer to that template throughout files like [bokeh/scheduler.py](https://github.com/dask/distributed/blob/master/distributed/bokeh/scheduler.py) whenever we pick out colors or set templates.
