### ISSUE TITLE
Add custom HTTP routes to Scheduler

### ISSUE THREAD

**Issue by psontag** [dask/distributed#3794]
I would like to add a custom HTTP route to the scheduler from a Python file located somewhere on my disk. The routes are currently configured like this:

```yaml
distributed:
  scheduler:
    http:
      routes:
        - distributed.http.scheduler.prometheus
        - distributed.http.scheduler.info
        - distributed.http.scheduler.json
        - distributed.http.health
        - distributed.http.proxy
        - distributed.http.statics
        - /path/to/my/file/my_route.py
```

If I understand the code correctly we currently only support the `absolute path` for the module import. 
Is there another way to get his working? 
If not I would be willing to contribute a change to also support imports from a fully qualified path.
