### ISSUE TITLE
Proposal: Update colour scheme for `bytes stored` dashboard component

### ISSUE THREAD

**Issue by KrishanBhasin** [dask/distributed#3799]
Currently, the dashboard component that shows the number of bytes stored by each worker, has a simple colour scheme:
- red if it has exceeded the set limits
- orange if it has exceeded 50% of limits
- blue otherwise
https://github.com/dask/distributed/blob/95228dc2d480aa35dc6521cb46bdb34983583faa/distributed/dashboard/components/scheduler.py#L790-L795

I would find it more useful if the colours reflected where the workers sat compared to the `target`/`spill`/`pause`/`terminate` limits that can be set in Dask's configuration.

https://distributed.dask.org/en/latest/worker.html#memory-management

I would be happy to contribute a PR to change this behaviour if you agree this would be a useful change. (I would also appreciate it if you offered opinions on what colours to use)

**Comment by jacobtomlinson** [comment]
That sounds totally reasonable to me.

I would suggest blue for target, orange for spill, red for pause and black for terminate. It's unlikely you would see terminate represented on the dashboard anyway as the worker would be restarted.

**Comment by mrocklin** [comment]
There is some value to having a warning level before we get to any
remediation strategy like spilling

**Comment by jacobtomlinson** [comment]
Hmm thinking on it more I'm not sure what I said makes sense. Looking at the docs we have the following default limits:

```yaml
distributed:
  worker:
    # Fractions of worker memory at which we take action to avoid memory blowup
    # Set any of the lower three values to False to turn off the behavior entirely
    memory:
      target: 0.60  # target fraction to stay below
      spill: 0.70  # fraction at which we spill to disk
      pause: 0.80  # fraction at which we pause worker threads
      terminate: 0.95  # fraction at which we terminate the worker
```

The target threshold is `0.6` and the spill threshold is `0.7`. So we could do with another color to have in between, perhaps yellow? This satisfies @mrocklin's request for a warning but aligns better with the thresholds.

I think it still makes sense to use orange once we start spilling and red when we pause.
