### ISSUE TITLE
Adding TLS/SSL to Dask Scheduler, Workers, and Jupyter

### ISSUE THREAD

**Issue by rileyhun** [dask/distributed#3997]
**What happened**:
I am trying to add TLS/SSL Security to my Dask Cluster hosted on Google Kubernetes Engine, installed using helm. I added the fields to the config yaml file and then applied the changes to the Dask Cluster, but I'm still able to freely access my Dask cluster without having to add a security object. 

I'm trying to accomplish this in the documentation [1]

I also reviewed this similar issue [2] 

[1] https://distributed.dask.org/en/latest/tls.html
[2] https://github.com/dask/dask/issues/5079

While it is explained how to access a secured Dask cluster, there isn't much comprehensive information in the docs on how to add a security layer

**What you expected to happen**:
I was expecting to be prohibited from accessing the Dask cluster without invoking a security object, and then to be able to access the cluster when providing a security object

**Minimal Complete Verifiable Example**:

1. `helm repo add dask https://helm.dask.org`
2. Access k8s cluster
`gcloud container clusters get-credentials ${RELEASE} --region ${REGION}`
3. Install Dask workers
`helm install ${RELEASE} dask/dask --set scheduler.serviceType=LoadBalancer`
4. Create Security Files
`openssl req -newkey rsa:4096 -nodes -sha256 -x509 -days 3650 -nodes -out myca.pem -keyout mykey.pem`
5. Yaml File w/ Config Changes:

```
distributed:
  comm:
    default-scheme: tls
    require-encryption: True
    tls:
      ca-file: myca.pem
      scheduler:
        key: mykey.pem
        cert: myca.pem
      worker:
        key: mykey.pem
        cert: myca.pem
      client:
        key: mykey.pem
        cert: myca.pem

worker:
  name: worker
  allowed-failures: 5
  replicas: 10
  resources:
    limits:
      cpu: 2
      memory: 10G
    requests:
      cpu: 2
      memory: 10G
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: numba xarray joblib -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: >
        s3fs dask-ml pandas lz4 numpy dask distributed gcsfs SQLAlchemy google-cloud-storage pyarrow mlflow keras
        tensorflow prefect aiofile aiohttp asyncio gcloud-aio-storage pyspark --upgrade

# We want to keep the same packages on the worker and jupyter environments
jupyter:
  enabled: true
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: numba xarray matplotlib joblib -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: >
        s3fs dask-ml pandas lz4 numpy dask distributed gcsfs SQLAlchemy google-cloud-storage pyarrow mlflow keras
        tensorflow prefect aiofile aiohttp asyncio gcloud-aio-storage pyspark --upgrade

scheduler:
  allowed-failures: 5
  env:
    - name: EXTRA_PIP_PACKAGES
      value: >
        s3fs dask-ml pandas lz4 numpy dask distributed gcsfs SQLAlchemy google-cloud-storage pyarrow mlflow keras
        tensorflow prefect aiofile aiohttp asyncio gcloud-aio-storage pyspark --upgrade
```

6. Apply Config Changes
`helm upgrade ${RELEASE} dask/dask -f dask_config.yaml --set scheduler.serviceType=LoadBalancer --version 4.1.0`

**Anything else we need to know?**:
N/A

**Environment**:

- Dask version: 2.21
- Python version: 3.7.4
- Operating System: macOSX
- Install method (conda, pip, source): pip
