### ISSUE TITLE
Add the heartbeat_interval variable to scheduler Parameters

### ISSUE THREAD

**Issue by garanews** [dask/distributed#4083]
With the https://github.com/dask/distributed/pull/3896 it was tuned the heartbeat_interval and correlated to number of workers:

![image](https://user-images.githubusercontent.com/16938405/91578255-34bee980-e94a-11ea-8749-249a978b5f6e.png)

I think it would be useful have the heartbeat_interval   as a Parameter.
With few workers the heartbeat messages are flooding everything and is hard to debug code:

![image](https://user-images.githubusercontent.com/16938405/91578839-07bf0680-e94b-11ea-93e5-9b48223a41ac.png)

**Comment by mrocklin** [comment]
Correct, right now heartbeat intervals are adaptive based on the number of workers, and there is no option to make this configurable.  

In principle having a configuration value that defaulted to "auto" which would imply the current behavior seems sensible to me.  

Short term, you could also change your logging level.  I tend to use INFO by default.

**Comment by garanews** [comment]
Thanks @mrocklin , in case I would set logging INFO I am reading here https://docs.dask.org/en/latest/configuration.html and see that is possible to set with YAML, with system ENV or inline.
I am wondering if is possible to pass it as command.
For example, this is docker-compose of worker:
```
  worker01:
    build:
      context: .
      dockerfile: ./compose/local/dask/Dockerfile
      args:
        - http_proxy
        - https_proxy
    image: daskdev/dask
    hostname: dask-worker
    command:
      [
        "dask-worker",
        "--preload",
        "/tmp/daskworkerinit.py",
        "--nthreads",
        "1",
        "--nprocs",
        "1",
        "--memory-limit",
        "3G",
        "tcp://scheduler:8786",
      ]
```

So I would pass the logging to scheduler:
```
  scheduler:
    build:
      context: .
      dockerfile: ./compose/local/dask/Dockerfile
      args:
        - http_proxy
        - https_proxy
    image: daskdev/dask
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]
    networks:
      - elastic
```

But not sure if is possible and how :)
