### ISSUE TITLE
Data loss with `DataFrame.set_index(.., shuffle="disk")`

### ISSUE THREAD

**Issue by elephantum** [dask/distributed#4386]
**What happened**:
`DataFrame.set_index(..., shuffle="disk")` is loosing significant amount of data when multiple workers are used.

I.e. length of result dataframe is much smaller than length of initial dataframe.

**What you expected to happen**:

Length of dataframes before and after of `set_index` to be the same.

**Minimal Complete Verifiable Example**:

```python
cluster = dask_kubernetes.KubeCluster.from_yaml('worker.yaml', name=f'{os.getenv("HOSTNAME")}-dask', n_workers=6)
client = Client(cluster)

test_ddf = dd.from_pandas(pd.DataFrame({
    'uuid': [str(uuid.uuid4()) for i in range(10000)],
}), chunksize=100)

len(test_ddf)
# 10000

len(test_ddf.set_index('uuid'))
# 10000

len(test_ddf.set_index('uuid', shuffle='disk'))
# 1669
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2.26.0
- Python version: 3.8.5.final.0
- Operating System: Linux
- Install method (conda, pip, source): conda

{'host': {'python': '3.8.5.final.0',
  'python-bits': 64,
  'OS': 'Linux',
  'OS-release': '5.4.0-51-generic',
  'machine': 'x86_64',
  'processor': 'x86_64',
  'byteorder': 'little',
  'LC_ALL': 'None',
  'LANG': 'None'},
 'packages': {'python': '3.8.5.final.0',
  'dask': '2.26.0',
  'distributed': '2.26.0',
  'msgpack': '1.0.0',
  'cloudpickle': '1.6.0',
  'tornado': '6.0.4',
  'toolz': '0.10.0',
  'numpy': '1.19.1',
  'lz4': '3.1.0',
  'blosc': None}}

**Comment by elephantum** [comment]
Also, it seems that someone else has the same issue in 2.22.0

**Comment by elephantum** [comment]
Issue is reproducible on 2020.12.0

**Comment by jrbourbeau** [comment]
Thanks for raising an issue and providing a nice example @elephantum! 

I am not able to reproduce the same issue using the latest development versions of dask and distributed (i.e. each `len` computation returns 10,000):

```python
In [1]: import uuid
   ...: import pandas as pd
   ...: import dask.dataframe as dd
   ...: from dask.distributed import Client
   ...:
   ...:
   ...: with Client() as client:
   ...:     test_ddf = dd.from_pandas(pd.DataFrame({
   ...:         'uuid': [str(uuid.uuid4()) for i in range(10000)],
   ...:     }), chunksize=100)
   ...:
   ...:     print(len(test_ddf))
   ...:     print(len(test_ddf.set_index('uuid')))
   ...:     print(len(test_ddf.set_index('uuid', shuffle='disk')))
   ...:
10000
10000
10000
```

Could you try with the latest `master` branches?

**Comment by elephantum** [comment]
@jrbourbeau ok, I will try.

But, if I understand correctly you're testing with local client. In this setup it works for me as well.

Issue is reproducible when you have several workers on different machines (or in different docker containers).

Will it help if I provide `docker-compose` file to reproduce the issue?

**Comment by elephantum** [comment]
@jrbourbeau this is the way to reproduce the issue without k8s cluster: https://gist.github.com/elephantum/ed9975ac4e07b8bd59135e0bc8dc8ce8

**Comment by jrbourbeau** [comment]
Thanks @elephantum, either I or another Dask maintainer will investigate. Just FYI folks who would normally look into this are beginning to take off for end-of-year holidays, so it may be a couple of weeks before someone is able to take a look

**Comment by elephantum** [comment]
@jrbourbeau can I help somehow with this issue?

**Comment by quasiben** [comment]
I tried this with manually starting workers on my local machine (not using Client) and was unable to reproduce.  Perhaps there is something going on with writing to "disk" with docker ?  Something things you could try:

- Mount and configure a [temporary directory](https://docs.dask.org/en/latest/configuration-reference.html#dask.temporary-directory) for dask
- Run with debug logging `DASK_LOGGING__DISTRIBUTED=debug` and see if there's anything in the logging output

**Comment by elephantum** [comment]
@quasiben Is it possible that in your case all local workers use the same partd instance?

I believe that this is a key part.

I will try your suggestions and comment with results.

**Comment by elephantum** [comment]
Nothing in the log files with `DASK_LOGGING__DISTRIBUTED=debug` that can indicate to some obvious error.

Also I do not believe that this is a docker related issue.

If I would to guess, then I would say that this is an issue when several `partd` instances are started, but only one is used to collect results.

If I start only one worker in docker: no data loss. Two: I get half the data, and so on.

1 worker: 10000/10000
2 workers: 4881/10000
3 workers: 3363/10000
4 workers: 2547/10000

**Comment by elephantum** [comment]
Issue can be reproduced with dask version = 2021.1.1

**Comment by quasiben** [comment]
Disk shuffling, I believe is intended for single machine use or perhaps more precisely shared filesystem usage.  So I think you will need to mount the same directory to all the workers and the scheduler.  Something like the following:

```
services:
  scheduler:
    image: daskdev/dask:2021.1.1
    command: dask-scheduler
    volumes:
      - ./test.py:/srv/test.py
      - <full-path>/temp:/srv/temp
    environment:
      - DASK_TEMPORARY_DIRECTORY=/srv/temp
      - <full-path>/sch:/srv/sch

  wrk1:
    image: daskdev/dask:2021.1.1
    command: dask-worker tcp://scheduler:8786 --local-directory /srv/temp
    volumes:
      - <full-path>/temp:/srv/temp

  wrk2:
    image: daskdev/dask:2021.1.1
    command: dask-worker tcp://scheduler:8786 --local-directory /srv/temp
    volumes:
      - <full-path>/temp:/srv/temp
```

My guess is that disk shuffling is not really designed for docker/k8s but rather bare metal usage.  I would also say probably not even in the NFS case, as NFS tends to be slow
