### ISSUE TITLE
Configuration File

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#463]
Continuation of https://github.com/dask/distributed/issues/58

I think it's now time to have a configuration file.  There are a few options that may be nicer to manage on a per-machine basis rather than in various command line options (though these will remain dominant) and hard coded settings.

Here are a few:

1.  Logging levels for dask
2.  Logging levels for the bokeh web application
3.  Compression 
4.  Ports for the scheduler, json, web interface, etc..
5.  Whitelisted ports for bokeh (though this is now open by default)
6.  Whether or not to use PDB when an error occurs (I use this for debugging)

Some open questions:

1.  Where do we put this file?  I'm thinking `~/.dask/config`
2.  What format do we use, JSON, YAML, TOML, INI?
3.  Are there other options that people find themselves often setting that we would want to include?  We could also just include *all* options available through the CLI
4.  Desired nesting level?  For example

    ```python
    'scheduler': {'port': 8786,
                  'bokeh': 8787}, 
    ...
    ```
    vs 
    ```python
    'scheduler-port': 8786,
    'scheduler-bokeh': 8787,
    ...
    ```

@quasiben I would value your feedback in particular here.

I don't have much scar tissue on this topic.

**Comment by mrocklin** [comment]
Currently going ahead with YAML.  So far I'm only putting in options that I use personally.  Planning to wait until people need more to add more:

```yaml
logging:
  distributed: info
  distributed.executor: warning
  bokeh: critical

compression: auto

# Scheduler specific options

bandwidth: 100000000    # 100 MB/s estimated worker-worker bandwidth
allowed-failures: 3     # number of retries before a task is considered bad
pdb-on-err: False       # enter debug mode on scheduling error
transition-log-length: 100000
```
