### ISSUE TITLE
SSL error (certs?) when installing `distributed` from conda-forge on Windows, Python 3.7 using Github Actions

### ISSUE THREAD

**Issue by eriknw** [dask/distributed#5409]
**What happened**:

`afar` CI on Github Actions fails, because it can't import `distributed` due to an openssl (cert?) issue:

https://github.com/eriknw/afar/pull/31/checks?check_run_id=3873207996

**What you expected to happen**:

I expect to be able to import `distributed` for this CI configuration.

**Anything else we need to know?**:

Because [`afar`](https://github.com/eriknw/afar) is so magical, I test it with environments created with `pip` and `conda-forge` on Linux, OS X, and Windows for Python 3.7, 3.8, and 3.9.  It turns out this can serve as a decent smoke test for checking whether `distributed` can be installed and used for typical CI jobs on Github Actions.

Currently, all are passing except `conda`, Windows, 3.7.  See test matrix and failure here:

https://github.com/eriknw/afar/pull/31/checks?check_run_id=3873207996

Simply trying to import `distributed` results in this error:
<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Miniconda\envs\afar\lib\site-packages\distributed\__init__.py", line 8, in <module>
    from .actor import Actor, ActorFuture
  File "C:\Miniconda\envs\afar\lib\site-packages\distributed\actor.py", line 5, in <module>
    from .client import Future
  File "C:\Miniconda\envs\afar\lib\site-packages\distributed\client.py", line 53, in <module>
    from .batched import BatchedSend
  File "C:\Miniconda\envs\afar\lib\site-packages\distributed\batched.py", line 10, in <module>
    from .core import CommClosedError
  File "C:\Miniconda\envs\afar\lib\site-packages\distributed\core.py", line 24, in <module>
    from .comm import (
  File "C:\Miniconda\envs\afar\lib\site-packages\distributed\comm\__init__.py", line 25, in <module>
    _register_transports()
  File "C:\Miniconda\envs\afar\lib\site-packages\distributed\comm\__init__.py", line 17, in _register_transports
    from . import inproc, tcp, ws
  File "C:\Miniconda\envs\afar\lib\site-packages\distributed\comm\tcp.py", line 19, in <module>
    from tornado import netutil
  File "C:\Miniconda\envs\afar\lib\site-packages\tornado\netutil.py", line 34, in <module>
    _client_ssl_defaults = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
  File "C:\Miniconda\envs\afar\lib\ssl.py", line 589, in create_default_context
    context.load_default_certs(purpose)
  File "C:\Miniconda\envs\afar\lib\ssl.py", line 490, in load_default_certs
    self._load_windows_store_certs(storename, purpose)
  File "C:\Miniconda\envs\afar\lib\ssl.py", line 482, in _load_windows_store_certs
    self.load_verify_locations(cadata=certs)
ssl.SSLError: unknown error (_ssl.c:4034)
```
</details>

**Environment:**
<details>
<summary>Conda environment</summary>

```
    package                    |            build
    ---------------------------|-----------------
    atomicwrites-1.4.0         |     pyh9f0ad1d_0          10 KB  conda-forge
    attrs-21.2.0               |     pyhd8ed1ab_0          44 KB  conda-forge
    click-8.0.3                |   py37h03978a9_0         146 KB  conda-forge
    cloudpickle-2.0.0          |     pyhd8ed1ab_0          24 KB  conda-forge
    colorama-0.4.4             |     pyh9f0ad1d_0          18 KB  conda-forge
    cytoolz-0.11.0             |   py37hcc03f2d_3         323 KB  conda-forge
    dask-core-2021.9.1         |     pyhd8ed1ab_0         768 KB  conda-forge
    distributed-2021.9.1       |   py37h03978a9_0         1.1 MB  conda-forge
    fsspec-2021.10.0           |     pyhd8ed1ab_0          85 KB  conda-forge
    heapdict-1.0.1             |             py_0           7 KB  conda-forge
    importlib-metadata-4.8.1   |   py37h03978a9_0          32 KB  conda-forge
    importlib_metadata-4.8.1   |       hd8ed1ab_0           4 KB  conda-forge
    iniconfig-1.1.1            |     pyh9f0ad1d_0           8 KB  conda-forge
    innerscope-0.5.0           |     pyhd8ed1ab_0          19 KB  conda-forge
    jinja2-3.0.2               |     pyhd8ed1ab_0          99 KB  conda-forge
    locket-0.2.0               |             py_2           6 KB  conda-forge
    markupsafe-2.0.1           |   py37hcc03f2d_0          25 KB  conda-forge
    more-itertools-8.10.0      |     pyhd8ed1ab_0          44 KB  conda-forge
    msgpack-python-1.0.2       |   py37h8c56517_1          80 KB  conda-forge
    packaging-21.0             |     pyhd8ed1ab_0          35 KB  conda-forge
    partd-1.2.0                |     pyhd8ed1ab_0          18 KB  conda-forge
    pluggy-1.0.0               |   py37h03978a9_1          25 KB  conda-forge
    psutil-5.8.0               |   py37hcc03f2d_1         362 KB  conda-forge
    py-1.10.0                  |     pyhd3deb0d_0          73 KB  conda-forge
    pyparsing-2.4.7            |     pyh9f0ad1d_0          60 KB  conda-forge
    pytest-6.2.5               |   py37h03978a9_0         465 KB  conda-forge
    pyyaml-5.4.1               |   py37hcc03f2d_1         160 KB  conda-forge
    sortedcontainers-2.4.0     |     pyhd8ed1ab_0          26 KB  conda-forge
    tblib-1.7.0                |     pyhd8ed1ab_0          15 KB  conda-forge
    toml-0.10.2                |     pyhd8ed1ab_0          18 KB  conda-forge
    toolz-0.11.1               |             py_0          46 KB  conda-forge
    tornado-6.1                |   py37hcc03f2d_1         648 KB  conda-forge
    typing_extensions-3.10.0.2 |     pyha770c72_0          28 KB  conda-forge
    yaml-0.2.5                 |       he774522_0          61 KB  conda-forge
    zict-2.0.0                 |             py_0          10 KB  conda-forge
    zipp-3.6.0                 |     pyhd8ed1ab_0          12 KB  conda-forge
    ------------------------------------------------------------
```
</details>

The Github Action setup is pretty standard: https://github.com/eriknw/afar/blob/b5eb31f8abda4e8c1abcd424244e19b2b2fee868/.github/workflows/test_conda.yml
<details>
<summary>test_conda.yml</summary>

```yaml
name: Test conda

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.7, 3.8, 3.9]  # , "3.7.10 1_73_pypy"]
        # exclude:
        #   - os: "windows-latest"
        #     python-version: "3.7.10 1_73_pypy"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          activate-environment: afar
      - name: Install dependencies
        run: |
          conda install -y -c conda-forge distributed pytest innerscope
          pip install -e .
      - name: PyTest
        run: |
          which python  # sanity check
          pytest
      - name: Notebook test
        run: |
          conda install -y -c conda-forge nbconvert jupyter
          jupyter nbconvert --to notebook --execute afar/tests/*ipynb
```
</details>

Is there an easy, known way to fix this?  I'm inclined to ignore the error, but it is pretty annoying.
