### ISSUE TITLE
AMM is incompatible with actors

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#7059]
With
```yaml
distributed:
  scheduler:
    active-memory-manager:
      start: true
      interval: 0.01s
```

Several tests in test_actor.py become very unstable.
For example `test_worker_actions` now fails frequently with

```
>   value = getattr(self.state.actors[actor], attribute)
E   KeyError: 'Counter-73f67bdc-7ad0-43af-9c4a-176532f810ca'
```
