### ISSUE TITLE
Assign tasks to idle workers rather than queuing them

### ISSUE THREAD

**Issue by NakulK48** [dask/distributed#7384]

**Comment by jacobtomlinson** [comment]
I'm going to transfer this issue over to dask/distriubuted as it's not really related to the Kubernetes deployment tooling.

@NakulK48 could you share an example of the code you're running to submit the tasks?

**Comment by fjetter** [comment]
We are indeed assigning tasks greedly to workers if they are available. once new workers join, we are rebalancing s.t. every worker has a roughly equal load.

Note: The latest releases introduced a change to this logic (I believe starting 2022.11.0). What version are you running?

**Comment by NakulK48** [comment]
This is the full scheduler spec - we are using 2022.10, so I can try 2022.11 and see if that improves things:

```yaml
  scheduler:
    service:
      ports:
      - name: tcp-comm
        port: 8786
        protocol: TCP
        targetPort: tcp-comm
      - name: http-dashboard
        port: 8787
        protocol: TCP
        targetPort: http-dashboard
      selector:
        dask.org/cluster-name: null
        dask.org/component: scheduler
      type: ClusterIP
    spec:
      serviceAccountName: research
      priorityClassName: dlf-workers
      containers:
      - args:
        - dask-scheduler
        - --host
        - 0.0.0.0
        env: []
        image: "ghcr.io/dask/dask:2022.10.0"
        livenessProbe:
          httpGet:
            path: /health
            port: http-dashboard
          initialDelaySeconds: 15
          periodSeconds: 20
        name: scheduler
        ports:
        - containerPort: 8786
          name: tcp-comm
          protocol: TCP
        - containerPort: 8787
          name: http-dashboard
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: http-dashboard
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "1"
            memory: 8Gi
  
```

**Comment by NakulK48** [comment]
Still the same issue I'm afraid - three tasks started and all of the other workers are idle.

**Comment by gjoseph92** [comment]
Can you create a reproducer for this in any way? Something that can run with a local cluster instead of k8s?

Are the tasks using resource restrictions or worker restrictions or anything like that? Also, do the tasks have any dependencies?

If the tasks don't have dependencies, I'd guess https://github.com/dask/distributed/issues/7274 would solve your problem. Probably all of the tasks are being submitted to the first worker that joins, and maybe once 3 workers have joined, the load-balancing algorithm (work stealing) no longer thinks it would be worth rebalancing them to new workers.

The work-stealing load-balancing algorithm is known to not perform that well when clusters scale up:
* https://github.com/dask/distributed/issues/4471
* https://github.com/dask/distributed/issues/5599

At a minimum, screenshots or a recording of the dashboard would be helpful in diagnosing this.

**Comment by NakulK48** [comment]
Here's the dashboard, showing the idle workers: 

<img width="783" alt="image" src="https://user-images.githubusercontent.com/6199511/207286578-b3b2e950-1869-46ef-9e71-a0e085b52801.png">

Anything in particular you'd like to see? Unfortunately this wouldn't be reproducible on a local dask cluster, because you wouldn't see the same behaviour around machines spinning up at different times.

**Comment by NakulK48** [comment]
Here's an interesting thing:

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/6199511/207291281-ceb5d2b3-fe3b-4274-8ccb-1ab2063b6790.png">

Note how it claims all three tasks are `processing` (but if I look at the S3 bucket where it should be writing, it's not processing at all).

**Comment by NakulK48** [comment]
And one of the workers has -1 GPUs consumed...

<img width="630" alt="image" src="https://user-images.githubusercontent.com/6199511/207292834-7fa969d3-774b-4958-be47-3bfd2b55ce8c.png">

**Comment by NakulK48** [comment]
I don't think GIL should really enter into this. The intention is very much that only one task runs on any given worker at a time, because these are single-GPU machines and each task needs the whole GPU.

```yaml
  worker:
    replicas: null
    spec:
      serviceAccountName: research
      priorityClassName: dlf-workers
      containers:
      - args:
        - dask-worker
        - --name
        - $(DASK_WORKER_NAME)
        - --resources
        - GPU=1
        env: []
        image: null
        name: worker
        resources:
          limits:
            cpu: "3"
            memory: 14Gi
            nvidia.com/gpu: "1"
```

```python
        with dask.annotate(resources={"GPU": 1}):
            future = client.submit(
                <snip>
            )
            LOGGER.info("Submitting task %s for run %s", task_index, run_id)
            futures.append(future)
            fire_and_forget(future)
```
