### ISSUE TITLE
dataframe shuffle: Obscure failure if pyarrow is not installed

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#8265]
If pandas is installed but pyarrow isn't, p2p dataframe shuffle fails with a very obscure

`RuntimeError: P2P shuffling e3b0df60fbfc8044356bd67bb2dc2df4 failed during transfer phase`

This is reproduced e.g. by  `test_index_merge_p2p`.

You can get the use case with a conda env that looks as follows:
```yaml
name: dask-distributed
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - pip
  - pip:
      - dask
      - distributed
```

# Expected behaviour
The user should get a clean `ModuleNotFoundError`.

CC @hendrikmakait @graingert
