### ISSUE TITLE
Scheduler is busy 95% of CPU time with `distributed.protocol.pickle.dumps` on objects which should be trivial to pickle

### ISSUE THREAD

**Issue by jonded94** [dask/distributed#8767]
**Describe the issue**:

I have a pipeline with tasks that return a simple `pathlib.Path` object. We have around 60k tasks that, in this particular example, each should in principle only take a second or less and immediately return. This is because we have an idempotent pipeline stack and this is a validation/rerun on data which was already processed.

While doing that, unfortunately the scheduler reports tick durations of up to 3 seconds (!), the workers also report latencies to the scheduler of ~2.5s. This returns to normal values (i.e. a few ~ms) immediately as soon as all tasks are processed by the workers. 

On investigation, it became clear that for some reason, the scheduler has a huge problem with pickling and spends almost *all* of its CPU time there. This leads to the client, which is asking for results of the scheduled Futures (and immediately after getting them, tries to evicts them), not getting any result at all, only after everything is done by the workers. Then, the scheduler relaxes a bit again and slowly drains all the Future results to the client. This can get to a problem since completed tasks can accumulate unnecessarily on the workers and thereby OOM-crash them (which doesn't happen at all when this pipeline runs in the "regular" mode where a task takes much longer [>20min]).

Investigating with `py-spy` and `speedscope`:

![image](https://github.com/user-attachments/assets/257ee8f8-9598-4206-9f43-8843f20a50c2)
[speedscope2.json](https://github.com/user-attachments/files/16194941/speedscope2.json)

It seems like the scheduler spends >=95% of time in `distributed.protocol.pickle.dumps`. I was able to verify with `py-spy dump -lll`, which prints local variables, that the object that the scheduler pickles indeed is the expected `pathlib.Path` object. On this particular datatype that we pickle here, I benchmarked pickling with the exact same call, this took ~3-28µs per object.

In this example, the scheduler spends sometimes almost 11s (!) on this call; I'm a bit lost why.

- Do you have any idea how to debug / analyse this further? Are there any metrics that I can provide you?
- More general question: Was there ever a discussion / trial around making the scheduler multithreaded instead of concurrent? Currently, as soon as any particular component of the scheduler takes a lot of CPU time (the dashboard, scheduling logic, ...), this effectively kills the entire cluster. This is somewhat of a single point of failure and especially for larger pipelines, it could be very helpful to give the scheduler a whole bunch of threads for drastically greater performance
- Why is the scheduler pickling at all? I'm probably very wrong, but I was under the impression that the *client* pickles the tasks that should be executed, while the *workers* pickle the return values. The *scheduler* should be only there to send these bytes around very efficiently, or am I wrong here?

**Environment**:

- Dask version: 2024.7.0
- Python version: 3.10
- Operating System: Linux, Debian
- Install method (conda, pip, source): `poetry` / `pip`

**Comment by fjetter** [comment]
> More general question: Was there ever a discussion / trial around making the scheduler multithreaded instead of concurrent?

Well, the scheduling logic itself is already incredibly complex without dealing with thread safety so this will likely never happen. Generally speaking, the scheduler should handle a lot of traffic using asyncio but you are correct that this has flaws.

We are already employing additional threads to de/serialize code. We are not offloading _everything_ to a background thread, though. the heuristic is based on object size assuming that small objects are fast and offloading will not be worth it.

**Comment by fjetter** [comment]
The scheduler does not unpickle result values. However, what it does pickle/unpickle is the _code_ you are submitting. Do you have anything that could possibly be slow in your submit/compute calls?

**Comment by jonded94** [comment]
> However, what it does pickle/unpickle is the code you are submitting. Do you have anything that could possibly be slow in your submit/compute calls?

Okay, I digged again a bit deeper and indeed it seems to have to do with the submission of calls, not the return values, yes!

This is a stacktrace with variables visible from the scheduler while tasks are running and it's spending 95% of compute on `dumps`:
```
Thread 1 (active+gil): "MainThread"
    dumps (distributed/protocol/pickle.py:63)
        Arguments:
            x: (<functools.partial at 0x7f3c4703e4d0>, (<pathlib.Path at 0x7f3c31c8a490>), {})
        Locals:
            buffer_callback: <function at 0x7f3c284bd5a0>
            protocol: 5
            buffers: []
            dump_kwargs: {"protocol": 5, "buffer_callback": <builtin_function_or_method at 0x7f3c27845530>}
    create_pickled_sub_frames (distributed/protocol/core.py:79)
        Arguments:
            obj: <ToPickle at 0x7f3c276ef7c0>
    _encode_default (distributed/protocol/core.py:103)
        Arguments:
            obj: <ToPickle at 0x7f3c276ef7c0>
        Locals:
            offset: 1
    packb (msgpack/__init__.py:36)
        Arguments:
            o: [{"op": "compute-task", "key": "[...]", "run_id": 51279, "priority": (0, 2, 46105), "duration": 0.05542836272210015, "stimulus_id": "compute-task-1720773592.0381951", "who_has": {}, "nbytes": {}, "run_spec": <ToPickle at 0x7f3c276ef7c0>, "resource_restrictions": None, "actor": False, "annotations": {}, ...}]
        Locals:
            kwargs: {"default": <function at 0x7f3c284bf0a0>, "use_bin_type": True}
    dumps (distributed/protocol/core.py:109)
        Arguments:
            msg: [{"op": "compute-task", "key": "[...]", "run_id": 51279, "priority": (0, 2, 46105), "duration": 0.05542836272210015, "stimulus_id": "compute-task-1720773592.0381951", "who_has": {}, "nbytes": {}, "run_spec": <ToPickle at 0x7f3c276ef7c0>, "resource_restrictions": None, "actor": False, "annotations": {}, ...}]
    _to_frames (distributed/comm/utils.py:34)
    to_frames (distributed/comm/utils.py:50)
        Arguments:
            allow_offload: False
        Locals:
            _to_frames: <function at 0x7f3c32323eb0>
    write (distributed/comm/tcp.py:264)
        Arguments:
            self: <TCP at 0x7f3c31cb42b0>
            msg: [{"op": "compute-task", "key": "[...]", "run_id": 51279, "priority": (0, 2, 46105), "duration": 0.05542836272210015, "stimulus_id": "compute-task-1720773592.0381951", "who_has": {}, "nbytes": {}, "run_spec": <ToPickle at 0x7f3c276ef7c0>, "resource_restrictions": None, "actor": False, "annotations": {}, ...}]
            serializers: None
            on_error: "raise"
        Locals:
            stream: <IOStream at 0x7f3c31cb4760>
```

What we do on the client side is basically only this:
```
partialed_func = functools.partial(func, param1=[some pathlib.Path], param2=[some pathlib.Path], ...)
dask_client.map(partialed_func, [list of ~60k pathlib.Path's], key=[some client-side calculated keys])
```

The keys of each Future that are in the stacktrace above are redacted because we manually set them to some nicer values for debugging. The `partial` only has ~5 parameters. The reason why we use `partial` here at all is that sometimes we'd like to use function which have a clashing `kwarg` with `client.map`, therefore `kwargs` have to be supplied earlier.

What I would have suspected here is that the `partialed_func` is pickled *once* and then, each of the 60k `pathlib.Path`'s is also pickled. The result of both is then sent to the workers.

It seems to me from the first rows of the stacktrace
```
dumps (distributed/protocol/pickle.py:63)
        Arguments:
            x: (<functools.partial at 0x7f3c4703e4d0>, (<pathlib.Path at 0x7f3c31c8a490>), {})
```
that actually for *every* of the 60k `pathlib.Path`'s the entire function (with all its other "partialed" parameters) are pickled? This surely is immediately way more costly than pickling a single Path, that would take only microseconds.

>instead of using pickle.dumps I suggest to use distributed.protocol.dumps which is implementing much more complex logic and we may hit a bad case.

Not exactly sure what you mean here, `pickle.dumps` is called nowhere explicitly in our code. What I stated above is just what we saw what the schedulers seems to be doing internally after a `client.map`. And this indeed is the `distributed.protocol.dumps` you're speaking of.
